{
 "title": "JMeter Prometheus",
 "description": "A grafana dashboard to inspect jmeter metrics via prometheus exporter",
 "tags": [ "jmeter" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "interval", "label": "interval", "query": "30s,1m,5m,10m" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jmeter_threads{state=\"active\"})",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(Ratio_success[$interval]))",
     "legendFormat": "Throughput"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((rate(ResponseTime_sum{code=~\"2..\"}[$interval])/(rate(ResponseTime_count{code=~\"2..\"}[$interval])>0)))",
     "legendFormat": "Response time"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg(rate(Ratio_failure[$interval]))/avg(rate(Ratio_total[$interval])))",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Virtual Users vs OK/Fail",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(jmeter_threads{state=\"active\"})",
     "legendFormat": "Virtual Users"
    },
    {
     "expr": "sum(rate(Ratio_success[$interval]))",
     "legendFormat": "Request OK/sec"
    },
    {
     "expr": "sum(rate(Ratio_failure[$interval]))   ",
     "legendFormat": "Request Fail/sec"
    }
   ]
  },
  {
   "title": "Total Requests vs OK/Fail",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(sum(rate(Ratio_success[$interval]))/sum(rate(Ratio_total[$interval])))",
     "legendFormat": "OK"
    },
    {
     "expr": "(sum(rate(Ratio_failure[$interval]))/sum(rate(Ratio_total[$interval])))",
     "legendFormat": "Fail"
    },
    {
     "expr": "sum(rate(Ratio_total[$interval]))",
     "legendFormat": "Total/sec"
    }
   ]
  },
  {
   "title": "Avg. Response Time vs Virtual Users",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg((rate(ResponseTime_sum{code=~\"2..\"}[$interval])/(rate(ResponseTime_count{code=~\"2..\"}[$interval])>0)))",
     "legendFormat": "Avg Response Time"
    },
    {
     "expr": "sum(jmeter_threads{state=\"active\"})",
     "legendFormat": "Virtual Users"
    }
   ]
  },
  {
   "title": "Avg. Response Time vs OK/Fail",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg((rate(ResponseTime_sum{code=~\"2..\"}[$interval])/(rate(ResponseTime_count{code=~\"2..\"}[$interval])>0)))",
     "legendFormat": "Avg Response Time"
    },
    {
     "expr": "sum(rate(Ratio_success[$interval]))",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(rate(Ratio_failure[$interval]))   ",
     "legendFormat": "Fail"
    }
   ]
  },
  {
   "title": "OK",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(Ratio_success) by (label) " }
   ]
  },
  {
   "title": "Fails",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(Ratio_failure) by (label) " }
   ]
  },
  {
   "title": "Response times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Avg. response time (with fails)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": " avg (rate(ResponseTime_sum[$interval]) / (rate(ResponseTime_count[$interval])>0)) by (label)",
     "legendFormat": "{{label}} "
    }
   ]
  },
  {
   "title": "Pct response times",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(ResponseTime{code=~\"2..\"}) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(Ratio_success[$interval]))",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(rate(Ratio_failure[$interval]))",
     "legendFormat": "Fail"
    }
   ]
  },
  {
   "title": "by label",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(Ratio_total[$interval])) by (label)",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "by HTTP code",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (code) (rate(Ratio_total[$interval]))",
     "legendFormat": "HTTP {{code}}"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "targets": [
    {}
   ]
  },
  {
   "title": "by HTTP code",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(code) (rate(Ratio_failure[$interval]))",
     "legendFormat": "HTTP {{code}}"
    }
   ]
  },
  {
   "title": "by label",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (label) (rate(Ratio_failure[$interval]))",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Test farm",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 },
   "targets": [
    {}
   ]
  },
  {
   "title": "GC % time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{job=~\"jmeter\"}[1m])",
     "legendFormat": "{{instance}} - {{gc}} "
    }
   ]
  },
  {
   "title": "JVM heap  - free memory by pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(jvm_memory_pool_bytes_committed {job=~\"jmeter\"}) - (jvm_memory_pool_bytes_used{job=~\"jmeter\"}) ",
     "legendFormat": "{{instance}} - {{pool}}"
    }
   ]
  },
  {
   "title": "JVM heap -  used memory by pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(jvm_memory_pool_bytes_used{job=\"jmeter\"}) ",
     "legendFormat": "{{instance}} - {{pool}}"
    }
   ]
  },
  {
   "title": "JVM free memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(jvm_memory_bytes_max {job=\"jmeter\"}) - (jvm_memory_bytes_used{job=\"jmeter\"})",
     "legendFormat": "{{instance}} - {{area}}"
    }
   ]
  }
 ]
}